[Icon Theme]
Name=Sardi Mono Orange
Comment=Simple and flat icon theme with long shadow - git
Inherits=Sardi Mono,Sardi,Numix-Circle,Numix,gnome,hicolor
Example=folder

# Directory list
Directories=scalable/actions,scalable/places,scalable/status

[scalable/actions]
Size=512
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[scalable/places]
Size=512
Context=Places
Type=Scalable
MinSize=16
MaxSize=512

[scalable/status]
Size=512
Context=Status
Type=Scalable
MinSize=16
MaxSize=512
